export const LOADING='LOADING';
export const RESULT='RESULT';
export const RESULT_LOADED = 'RESULT_LOADED' ;
export const INCREASE_CURRENT_PAGE = 'INCREASE_CURRENT_PAGE';
export const RESET_CURRENT_PAGE = 'RESET_CURRENT_PAGE';
export const LOAD_MORE = 'LOAD_MORE';

